package br.com.mestres.ensino.webapp.spring.persistence.model;

// Generated 05/08/2014 23:00:01 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlunoHora generated by hbm2java
 */
@Entity
@Table(name = "aluno_hora", catalog = "mestresensino")
public class AlunoHora implements java.io.Serializable {

	private Integer id;
	private Aluno aluno;
	private Integer quantidade;
	private Date dataInclusao;

	public AlunoHora() {
	}

	public AlunoHora(Aluno aluno, Date dataInclusao) {
		this.aluno = aluno;
		this.dataInclusao = dataInclusao;
	}

	public AlunoHora(Aluno aluno, Integer quantidade, Date dataInclusao) {
		this.aluno = aluno;
		this.quantidade = quantidade;
		this.dataInclusao = dataInclusao;
	}

	public AlunoHora(Aluno aluno, Integer quantidade) {
		this.aluno = aluno;
		this.quantidade = quantidade;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aluno_id", nullable = false)
	public Aluno getAluno() {
		return this.aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	@Column(name = "quantidade")
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_inclusao", nullable = false, length = 19)
	public Date getDataInclusao() {
		return this.dataInclusao;
	}

	public void setDataInclusao(Date dataInclusao) {
		this.dataInclusao = dataInclusao;
	}

}
