package br.com.mestres.ensino.webapp.spring.persistence.model;

// Generated 05/08/2014 23:00:01 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AlunoHora generated by hbm2java
 */
@Entity
@Table(name = "aluno_hora", catalog = "mestresensino")
public class AlunoHora extends BaseEntity{

	private Aluno aluno;
	private Integer quantidade;

	public AlunoHora() {
	}

	public AlunoHora(Aluno aluno) {
		this.aluno = aluno;
	}

	public AlunoHora(Aluno aluno, Integer quantidade) {
		this.aluno = aluno;
		this.quantidade = quantidade;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "aluno_id", nullable = false)
	public Aluno getAluno() {
		return this.aluno;
	}

	public void setAluno(Aluno aluno) {
		this.aluno = aluno;
	}

	@Column(name = "quantidade")
	public Integer getQuantidade() {
		return this.quantidade;
	}

	public void setQuantidade(Integer quantidade) {
		this.quantidade = quantidade;
	}

}
