package br.com.mestres.ensino.webapp.spring.persistence.model;

// Generated 01/08/2014 01:15:09 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Professor generated by hbm2java
 */
@Entity
@Table(name = "professor", catalog = "mestresensino")
public class Professor implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String telefone;
	private String endereco;
	private String email;
	
	@JsonIgnore
	private Set<Aula> aulas = new HashSet<Aula>(0);

	public Professor() {
	}

	public Professor(String nome, Set<Aula> aulas) {
		this.nome = nome;
		this.aulas = aulas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome")
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "professor")
	public Set<Aula> getAulas() {
		return this.aulas;
	}

	public void setAulas(Set<Aula> aulas) {
		this.aulas = aulas;
	}

	@Column(name = "telefone")
	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	@Column(name = "endereco")
	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "email")
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
