package br.com.mestres.ensino.webapp.spring.persistence.model;

// Generated 05/08/2014 23:00:01 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name = "sala", catalog = "mestresensino")
public class Sala extends BaseEntity{

	private Integer numero;
	private Integer assentosDisponiveis;
	
	@JsonIgnore
	private Set<Aula> aulas = new HashSet<Aula>(0);

	public Sala() {
	}

	public Sala(Integer numero, Set<Aula> aulas) {
		this.numero = numero;
		this.aulas = aulas;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sala")
	public Set<Aula> getAulas() {
		return this.aulas;
	}

	public void setAulas(Set<Aula> aulas) {
		this.aulas = aulas;
	}

	@Column(name = "assentos_disponiveis")
	public Integer getAssentosDisponiveis() {
		return assentosDisponiveis;
	}

	public void setAssentosDisponiveis(Integer assentosDisponiveis) {
		this.assentosDisponiveis = assentosDisponiveis;
	}

}
