package br.com.mestres.ensino.webapp.spring.persistence.model;

// Generated 01/08/2014 01:15:09 by Hibernate Tools 4.0.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sala generated by hbm2java
 */
@Entity
@Table(name = "sala", catalog = "mestresensino")
public class Sala implements java.io.Serializable {

	private Integer id;
	private Integer numero;
	private Set<Aula> aulas = new HashSet<Aula>(0);

	public Sala() {
	}

	public Sala(Integer numero, Set<Aula> aulas) {
		this.numero = numero;
		this.aulas = aulas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "numero")
	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sala")
	public Set<Aula> getAulas() {
		return this.aulas;
	}

	public void setAulas(Set<Aula> aulas) {
		this.aulas = aulas;
	}

}
